vich_uploader:
    db_driver: orm
    mappings:
       questionnaires:
            uri_prefix: /images/questionnaires
            upload_destination: '%kernel.project_dir%/public/images/questionnaires'
